# Generated by Django 2.2.2 on 2019-07-02 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('h_name', models.CharField(max_length=80, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'hobby',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('n_name', models.TextField()),
                ('alter', models.IntegerField()),
                ('wohnort', models.TextField(blank=True, null=True)),
                ('anzeigename', models.CharField(blank=True, max_length=80, null=True)),
                ('einkommen', models.BigIntegerField()),
            ],
            options={
                'db_table': 'nutzer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Beziehung',
            fields=[
                ('id1', models.ForeignKey(db_column='id1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='second', serialize=False, to='social_site.Nutzer')),
                ('art', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'beziehung',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Brillentraeger',
            fields=[
                ('id', models.ForeignKey(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='social_site.Nutzer')),
            ],
            options={
                'db_table': 'brillentraeger',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Istfan',
            fields=[
                ('id1', models.ForeignKey(db_column='id1', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='social_site.Nutzer')),
            ],
            options={
                'db_table': 'istfan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Uebtaus',
            fields=[
                ('nutzerid', models.ForeignKey(db_column='nutzerid', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='social_site.Nutzer')),
            ],
            options={
                'db_table': 'uebtaus',
                'managed': False,
            },
        ),
    ]
